/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 room.gltf 
Author: Sevda Sabirova (https://sketchfab.com/sevdasabirova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/interiorroom-f50eac065c084e3eb1414b4fd7b9e17d
Title: Interior/Room
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/room.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={440.441}>
          <mesh
            geometry={nodes.Cube_Pol_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Cube_Sheli_0.geometry}
            material={materials.Sheli}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={440.441}>
          <mesh
            geometry={nodes.Cube009_Carpet_0.geometry}
            material={materials.Carpet}
          />
          <mesh
            geometry={nodes.Cube009_Carpet2_0.geometry}
            material={materials.Carpet2}
          />
        </group>
        <group
          position={[2.274, -30.418, -298.847]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        >
          <mesh
            geometry={nodes.Cube022_Zabaveski_0.geometry}
            material={materials.Zabaveski}
          />
          <mesh
            geometry={nodes.Cube022_Material_0.geometry}
            material={materials.Material}
          />
        </group>
        <group
          position={[0, 180.154, 35.733]}
          rotation={[-Math.PI / 2, 0, -0.809]}
          scale={10.571}
        >
          <mesh
            geometry={nodes.Plane002_Material003_0.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Plane002_Material004_0.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          position={[87.656, 180.154, -45.224]}
          rotation={[-Math.PI / 2, 0, 0.295]}
          scale={10.571}
        >
          <mesh
            geometry={nodes.Plane004_Material003_0.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Plane004_Material004_0.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          position={[0, 0, 0.479]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        >
          <mesh
            geometry={nodes.Cube023_Derevo_0.geometry}
            material={materials.Derevo}
          />
          <mesh
            geometry={nodes.Cube023_Material001_0.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group
          position={[0, 365.804, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={434.083}
        >
          <mesh
            geometry={nodes.Cube002_wall_0.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.Cube002_Glass1_0.geometry}
            material={materials.Glass1}
          />
        </group>
        <mesh
          geometry={nodes.Cube004_sofa_0.geometry}
          material={materials.sofa}
          position={[204.792, 167.712, -342.741]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube005_sofa_0.geometry}
          material={materials.sofa}
          position={[204.792, 167.712, -342.741]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube006_Derevo_0.geometry}
          material={materials.Derevo}
          position={[204.792, 167.712, -342.741]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube007_Pillow_0.geometry}
          material={materials.Pillow}
          position={[204.792, 167.712, -342.741]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube008_Pillow_0.geometry}
          material={materials.Pillow}
          position={[204.792, 167.712, -342.741]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder_Table2_0.geometry}
          material={materials.Table2}
          position={[-307.942, 233.56, -361.297]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder001_Gorshok_0.geometry}
          material={materials.Gorshok}
          position={[-307.942, 324.103, -361.297]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube010_sofa_0.geometry}
          material={materials.sofa}
          position={[-335.599, 167.712, 158.828]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube011_sofa_0.geometry}
          material={materials.sofa}
          position={[-335.599, 167.712, 158.828]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube012_Derevo_0.geometry}
          material={materials.Derevo}
          position={[-335.599, 167.712, 158.828]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube013_Pled_0.geometry}
          material={materials.Pled}
          position={[-335.599, 167.712, 158.828]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube014_Pillow_0.geometry}
          material={materials.Pillow}
          position={[-346.503, 167.712, 241.652]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube015_Table_0.geometry}
          material={materials.Table}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        />
        <mesh
          geometry={nodes.Cube016_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        />
        <mesh
          geometry={nodes.Cube017_Pol_0.geometry}
          material={materials.material}
          position={[0, 0, -96.325]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        />
        <mesh
          geometry={nodes.Cylinder002_Metall_0.geometry}
          material={materials.Metall}
          position={[-307.942, 444.053, -513.815]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder003_Metall_0.geometry}
          material={materials.Metall}
          position={[-307.942, 444.053, -513.815]}
          scale={100}
        />
        <mesh
          geometry={nodes.Sphere_LIght_0.geometry}
          material={materials.LIght}
          position={[-120.413, 529.287, -374.104]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={19.857}
        />
        <mesh
          geometry={nodes.Cube018_Metall_0.geometry}
          material={materials.Metall}
          position={[21.138, -57.674, -96.325]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        />
        <mesh
          geometry={nodes.Cube019_Metall_0.geometry}
          material={materials.Metall}
          position={[16.238, -57.674, -96.325]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        />
        <mesh
          geometry={nodes.Cube020_Metall_0.geometry}
          material={materials.Metall}
          position={[16.238, -57.674, -492.246]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        />
        <mesh
          geometry={nodes.Cube021_Zabaveski_0.geometry}
          material={materials.Zabaveski}
          position={[2.274, -30.418, -96.325]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={440.441}
        />
        <mesh
          geometry={nodes.Plane_Flower_0.geometry}
          material={materials.Flower}
          position={[-320.471, 506.408, -339.99]}
          scale={[21.487, 100, 100]}
        />
        <mesh
          geometry={nodes.Sphere001_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[-85.755, 212.437, -25.16]}
          rotation={[-Math.PI / 2, 0, 0.484]}
          scale={[14.424, 13.452, 13.452]}
        />
        <mesh
          geometry={nodes.Plane001_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[0, 188.926, -9.464]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={21.465}
        />
        <mesh
          geometry={nodes.Torus_Material005_0.geometry}
          material={materials["Material.005"]}
          position={[-2.708, 193.438, -4.049]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-7.147, 7.147, 7.147]}
        />
        <mesh
          geometry={nodes.Torus001_Material005_0.geometry}
          material={materials["Material.005"]}
          position={[-2.708, 193.438, -13.461]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-7.147, 7.147, 7.147]}
        />
        <mesh
          geometry={nodes.Plane003_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[0, 180.154, 35.733]}
          rotation={[-Math.PI / 2, 0, -0.809]}
          scale={10.571}
        />
        <mesh
          geometry={nodes.Plane005_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[87.656, 180.154, -45.224]}
          rotation={[-Math.PI / 2, 0, 0.295]}
          scale={10.571}
        />
        <mesh
          geometry={nodes.Torus002_Metall_0.geometry}
          material={materials.Metall}
          position={[133.867, 497.203, -434.223]}
          scale={[6.721, 9.833, 6.721]}
        />
        <mesh
          geometry={nodes.Plane006_Metall_0.geometry}
          material={materials.Metall}
          position={[-355.873, 92.41, 326.626]}
          rotation={[-Math.PI / 2, 0, -0.92]}
          scale={47.838}
        />
        <mesh
          geometry={nodes.Plane007_LIght_0.geometry}
          material={materials.LIght}
          position={[-383.915, 93.815, 347.96]}
          rotation={[-Math.PI / 2, 0, -0.92]}
          scale={47.838}
        />
        <mesh
          geometry={nodes.Cube024_Table2_0.geometry}
          material={materials.Table2}
          position={[-78.704, 140.642, -380.227]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={64.197}
        />
        <mesh
          geometry={nodes.Cube025_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[-78.704, 140.642, -380.227]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={64.197}
        />
        <mesh
          geometry={nodes.Sphere002_Derevo_0.geometry}
          material={materials.Derevo}
          position={[-85.755, 212.437, -25.16]}
          rotation={[-Math.PI / 2, 0, 0.484]}
          scale={[14.424, 13.452, 13.452]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/room.gltf");
